name: KeithJames T
favicon: null
layout_spectrum: 1
typography_spectrum: 0.64603
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cdcec9'
    - '#f0efed'
    - '#0d0d0f'
    - '#868a8d'
    - '#55585d'
  brandStrength: 0.6875
  lightness: 0.6875
  saturation: 0.9375
  rhythmicContrast: 0.75
purpose: []
