typography_spectrum: 0.64603
color:
  brandColors:
    - '#cdcec9'
    - '#f0efed'
    - '#0d0d0f'
    - '#868a8d'
    - '#55585d'
  brandStrength: 0.6875
  lightness: 0.6875
  saturation: 0.9375
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: KeithJames T
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
